name: 'olist_dwh'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'olist_dwh'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  olist_dwh:


